### ISSUE TITLE
Update branches

### ISSUE THREAD

**Issue by cgudea** [shivshav/RaSousVide-Android#21]
I think we should remove query-layout, use develop as our workhorse branch. I'll submit pull requests via develop branch.

Master will be the branch for public release, ie playstore releases.

**Comment by cgudea** [comment]
actually, maybe we should make develop public and master be the playstore releases? whats your opinion?

**Comment by shivshav** [comment]
I like the idea of leaving develop as a sort-of beta channel for releases
for now as long as it gets tagged appropriately with beta releases only at
working states
